// AUTO-GENERATED by scripts/fetch-wiki-images.mjs — do not edit by hand.
// Maps NBA player id (slug) -> Wikipedia lead-image thumbnail URL. Used as a
// fallback for players without an nbaPlayerId (older legends, iconic-team role
// players). Regenerate with: node scripts/fetch-wiki-images.mjs
export const NBA_WIKIPEDIA_IMAGES: Record<string, string> = {};
